site_name: Manchester HacSpace - CAD / CAM
pages:
- Home: index.md
- PCM Milling:
    - Overview: PCBMilling/index.md
    - Building PCB2GCode Windows: PCBMilling/Building-PCB2GCode-Win.md

theme: slate
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
